In [1]:
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy as np

Using Theano backend.
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.


In [2]:
train = pd.read_csv("review.csv",header=None,names=['review','sen'])

In [3]:
train.head()

review       sen
0  This movie is really not all that bad. But the...  positive
1  Vanilla Sky was a wonderfully thought out movi...  positive
2  Joseph Brady and Clarence Doolittle are two sa...  positive
3  10 ITEMS OR LESS was made in two weeks on a sh...  positive
4  I saw this movie first on the Berlin Film Fest...  positive

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [5]:
count_vectorizer = CountVectorizer(binary='true')
train12 = count_vectorizer.fit_transform(train['review'])
tfidf_data = TfidfTransformer(use_idf=False).fit_transform(train12)

In [6]:
tfidf_data.toarray()

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.05530013,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [54]:
train12.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
from keras.preprocessing.text import Tokenizer
t = Tokenizer()

In [55]:
t.fit_on_texts(train)

In [64]:
y

array([[  0.,   1.,   0., ...,   0.,   0.,   0.],
       [  0.,   7.,   4., ...,   0.,   0.,   0.],
       [  0.,  16.,  11., ...,   0.,   0.,   0.],
       ..., 
       [  0.,   8.,   0., ...,   0.,   0.,   0.],
       [  0.,  30.,   0., ...,   0.,   0.,   0.],
       [  0.,  17.,  14., ...,   1.,   1.,   0.]])

In [63]:
y = t.texts_to_matrix(train['review'], mode= 'count'from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
# fix random seed for reproducibility
numpy.random.seed(7))